name: SLR parser
on: [push]

jobs:
  test-LR0:
    name: Test LR0 automaton class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace with your Python version if needed

      - name: Install pip dependencies on testing environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest on grammar files
        run: |
          python -m pytest tests/SLR/test_LR0.py

  test-AST:
    name: Test parser and AST builder against test samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace with your Python version if needed

      - name: Install pip dependencies on testing environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest on grammar files
        run: |
          python -m pytest tests/AST/test_AST.py
